### ISSUE TITLE
Show the gender and current status (dead or not) of samples on highlight on map

### ISSUE THREAD

**Issue by thokall** [CGI-NRM/GenotypeCheck#13]
Make sure that more information is shown on map and table when matching data. 
Next to the genotype on the table seen in attached image there is room to display gender and status of samples. The same goes for the popup sample information on the map. 

![Screenshot from 2021-06-10 14-35-05](https://user-images.githubusercontent.com/6167270/121525890-26355080-c9f9-11eb-8a82-e4210cb4b580.png)

**Comment by LogFlames** [comment]
@thokall Would it be usefull to see this information (gender and status) in the match list aswell?
![Match list](https://user-images.githubusercontent.com/36220731/124476461-1e23c300-dda3-11eb-8af7-b6b9d1a48253.png)

**Comment by LogFlames** [comment]
This is now this pr: https://github.com/CGI-NRM/GenotypeCheck/pull/18

I added a parameter to the function generating the datatables that decides whether to add the gender and confirmed dead columns.
