### ISSUE TITLE
Update GPS conversion package and functions

### ISSUE THREAD

**Issue by thokall** [CGI-NRM/GenotypeCheck#15]
The way R handles GPS coordinate conversions has been altered and some functions and definitions have been depracated.
[Example](
https://github.com/CGI-NRM/GenotypeCheck/blob/develop/R/app.R#L589-L591)

Possible change along these lines using the sf (simple feature package)
  ```
library(rgdal)
library(sf)
# Convert GPS coordinates
    df_conv <- reactive({
        inPutGPS <- REFS[[input$gpsfrom]]
        outPutGPS <- REFS[[input$gpsto]]
        df <- df_sel()
        p1 <- st_as_sf(df, 
                       coords = c("Longitude", "Latitude"), 
                       crs = inPutGPS)
        p2 <- st_transform(p1, outPutGPS)
        p2
    })
```

**Comment by LogFlames** [comment]
The package has now been updated to sf in this pr.
[new-coordinate-package](https://github.com/CGI-NRM/GenotypeCheck/pull/16)
