### ISSUE TITLE
Remove unwanted files from the repo

### ISSUE THREAD

**Issue by thokall** [CGI-NRM/GenotypeCheck#3]
Make sure to use .ignore to avoid pushing unneeded information (.Rproj and locked files tthat starts with ~

**Comment by LogFlames** [comment]
This issue is fixed, the .gitignore is updated and the file is removed.

**Comment by LogFlames** [comment]
Decided to keep the GenotypeCheck.Rproj since it contains information to Rstudio regarding the build packet settings and it allows for users to clone the branch and build the packet for themselfs.
