### ISSUE TITLE
function all_of (tidyselect?)

### ISSUE THREAD

**Issue by thokall** [CGI-NRM/GenotypeCheck#7]
Trying the code using the workflow.R as follows:

`source("workflow.R")
`

but that requires the function all_of to be available. Make sure that the requirements are updated to make sure that users have everything installed.

**Comment by thokall** [comment]
Is the use of all_of to make sure that there is an error thrown if any of the values are missing.

**Comment by LogFlames** [comment]
Yes, it is to avoid a warning when running the code.
